'use client';
import { ArrowRight, BookOpen, Check, GitBranch, Globe2, Network, ShieldCheck, Sparkles } from 'lucide-react';
import type { Dispatch, SetStateAction } from 'react';
import type { View } from '../types';
import { AnalysisSettings, Modal } from './ui';

export default function AppModals({modal,onClose,url,setUrl,extraUrls,setExtraUrls,maxPages,setMaxPages,running,startAnalysis,setToast,view,setError,setTouring}:{modal:string;onClose:()=>void;url:string;setUrl:(value:string)=>void;extraUrls:string;setExtraUrls:(value:string)=>void;maxPages:number;setMaxPages:(value:number)=>void;running:boolean;startAnalysis:()=>void;setToast:(value:string)=>void;view:View;setError:(value:string)=>void;setTouring:Dispatch<SetStateAction<boolean>>}){
 return <Modal title={modal==='new'?'Map a new API':modal==='settings'?'Your analysis settings':'A little context. A lot of clarity.'} onClose={onClose}>
   {modal==='new'&&<><p className="modal-lead">Give Atlas your documentation. Explore what exists, what connects, and which IDs move between APIs.</p><label className="form-label">PRIMARY DOCUMENTATION URL<input autoFocus type="url" placeholder="https://docs.example.com/api" value={url} onChange={e=>setUrl(e.target.value)}/></label><label className="form-label">ADDITIONAL API SOURCES <span>OPTIONAL</span><textarea placeholder={'https://another-api.com/openapi.json\nOne URL per line · up to 3 additional sources'} value={extraUrls} onChange={e=>setExtraUrls(e.target.value)} rows={3}/></label><p className="form-hint"><GitBranch size={13}/>Add related APIs to discover potential cross-API ID dependencies.</p><AnalysisSettings maxPages={maxPages} setMaxPages={setMaxPages}/><button className="primary-button full-width" onClick={startAnalysis} disabled={running}><Sparkles size={16}/>Start analysis<ArrowRight size={16}/></button></>}
   {modal==='settings'&&<><p className="modal-lead">Control how deeply Atlas explores your documentation.</p><AnalysisSettings maxPages={maxPages} setMaxPages={setMaxPages}/><button className="primary-button full-width" onClick={()=>{onClose();setToast('Settings saved for your next analysis.')}}><Check size={15}/>Done</button></>}
   {modal==='help'&&<><p className="modal-lead">Atlas turns public API specifications into a map you can explore and study.</p><div className="help-steps">{[[Globe2,'01','Bring your documentation','Paste a public OpenAPI / Swagger specification or a documentation site with embedded API definitions. Add up to four APIs to investigate cross-API relationships.'],[Network,'02','Follow the connections','Explore entities in 2D or 3D. Open ID lineage to trace producer and consumer endpoints. Every connection includes evidence.'],[BookOpen,'03','Build your understanding','Use the 30-minute study path, inspect design patterns, and export the analysis to keep learning.']].map(([Icon,n,title,description])=>{const I=Icon as typeof Globe2;return <div key={String(n)}><span><I size={20}/></span><div><h3>{String(title)}</h3><p>{String(description)}</p></div></div>})}</div><div className="info-banner"><ShieldCheck size={20}/><span>Atlas reports what it can parse. Private pages, JavaScript-only sites, external references, and undocumented behavior may leave gaps. Inferred links always need review.</span></div><button className="outline-button full-width" onClick={()=>{onClose();if(view==='workspace'){setError('Open a project first, then start the tour.');return}setTouring(true)}}>Take the interactive tour</button><button className="primary-button full-width" onClick={()=>onClose()}>Let’s explore<ArrowRight size={15}/></button></>}
  </Modal>;
}
