import { useState } from 'react';
import { ArrowDownLeft, ArrowUpRight, ArrowRight, Box, Braces, Check, CheckCheck, ChevronRight, ExternalLink, GitBranch, KeyRound, Link2, X, Sparkles, Copy } from 'lucide-react';
import type { Analysis, Dependency, Entity } from '../types';
import { entityColor } from '../types';
import type { TraceDirection } from '../backtrack';

export function Status({status}:{status:string}){return <span className={`status-label ${status==='documented'?'verified':'inferred'}`}>{status==='documented'?<CheckCheck size={12}/>:<Sparkles size={11}/>} {status==='documented'?'Documented':'Inferred'}</span>}
export default function Inspector({analysis,entity,dependency,reviewable=false,onReview,onSelect,onClose,onDependency,onTrace}:{analysis:Analysis;entity:Entity|null;dependency:Dependency|null;reviewable?:boolean;onReview?:(link:Dependency,verdict:'confirmed'|'rejected'|null)=>void;onSelect:(id:string)=>void;onClose:()=>void;onDependency:(d:Dependency)=>void;onTrace:(id:string,direction:TraceDirection)=>void}){
 const [tab,setTab]=useState('overview');const [copied,setCopied]=useState(false);
 if(dependency){const source=analysis.entities.find(e=>e.id===dependency.source),target=analysis.entities.find(e=>e.id===dependency.target);return <aside className="inspector"><div className="inspector-label"><span>CONNECTION DETAILS</span><button className="icon-button" onClick={onClose} aria-label="Close details"><X size={15}/></button></div><div className="inspector-body"><div className="big-entity-icon"><Link2 size={23}/></div><h2>ID lineage</h2><p className="muted">Understand where this dependency comes from.</p><div className="lineage-card"><button onClick={()=>onSelect(dependency.source)}>{source?.name}<ArrowUpRight size={14}/></button><div className="lineage-wire"><ArrowRight size={15}/><code>{dependency.field}</code></div><button onClick={()=>onSelect(dependency.target)}>{target?.name}<ArrowUpRight size={14}/></button></div><Status status={dependency.status}/>{reviewable&&onReview&&<div className="link-review">{dependency.review==='confirmed'?<><span><CheckCheck size={13}/>Confirmed by you</span><button className="text-button" onClick={()=>onReview(dependency,null)}>Undo</button></>:dependency.status==='inferred'?<><span>Is this link real?</span><button className="outline-button" onClick={()=>onReview(dependency,'confirmed')}><Check size={13}/>Confirm</button><button className="outline-button" onClick={()=>onReview(dependency,'rejected')}><X size={13}/>Reject</button></>:null}</div>}<h4>WHY THEY CONNECT</h4><p className="detail-copy">{dependency.evidence}</p>{dependency.quote&&<blockquote>{dependency.quote}</blockquote>}{dependency.sourceOperation&&<><h4>PRODUCER → CONSUMER</h4>{[dependency.sourceOperation,dependency.targetOperation].map((id,i)=>{const op=analysis.operations.find(o=>o.id===id);return op?<div className="operation-mini" key={id}><span className="tiny-label">{i?'Consumes':'Produces'}</span><code><b className={`method ${op.method}`}>{op.method}</b>{op.path}</code></div>:null})}</>}<a className="source-button" href={dependency.sourceUrl} target="_blank" rel="noreferrer">Inspect source evidence<ExternalLink size={13}/></a></div><div className="inspector-note"><CheckCheck size={15}/>Every connection has a source.</div></aside>}
 if(!entity)return <aside className="inspector inspector-empty"><MouseIllustration/><h3>Follow your curiosity.</h3><p>Select an entity or connection to see its fields, dependencies, and the evidence behind it.</p></aside>;
 const color=entityColor(entity);const incoming=analysis.dependencies.filter(d=>d.target===entity.id&&d.type!=='operation');const outgoing=analysis.dependencies.filter(d=>d.source===entity.id&&d.type!=='operation');
 const ops=analysis.operations.filter(o=>entity.operationIds.includes(o.id));
 return <aside className="inspector"><div className="inspector-label"><span>ENTITY DETAILS</span><button className="icon-button" onClick={onClose} aria-label="Close details"><X size={15}/></button></div><div className="inspector-body"><div className="entity-title-line"><span className="big-entity-icon" style={{background:color.soft,color:color.color}}><Box size={23}/></span><span className="resource-badge">{entity.kind==='schema'?'Schema':'Resource'}</span></div><h2>{entity.name}</h2><p className="entity-description">{entity.description}</p><div className="entity-stats"><span><Braces size={13}/>{entity.fields.length} fields</span><span><Link2 size={13}/>{incoming.length+outgoing.length} connections</span>{entity.schemaNames&&<span><Box size={13}/>{entity.schemaNames.length} schemas grouped</span>}</div><div className="inspector-trace-actions"><button className="inspector-trace" onClick={()=>onTrace(entity.id,'prerequisites')}><GitBranch size={15}/>Needs to create<ArrowRight size={14}/></button><button className="inspector-trace" onClick={()=>onTrace(entity.id,'dependents')}><ArrowUpRight size={15}/>Used by<ArrowRight size={14}/></button></div><div className="inspector-tabs">{['overview','fields','endpoints'].map(t=><button className={tab===t?'active':''} key={t} onClick={()=>setTab(t)}>{t}</button>)}</div>
 {tab==='overview'&&<><h4><ArrowDownLeft size={13}/> DEPENDS ON <span>{incoming.length}</span></h4>{incoming.length?incoming.slice(0,16).map(d=><Relationship key={d.id} dependency={d} entity={analysis.entities.find(e=>e.id===d.source)} onClick={()=>onDependency(d)}/>):<p className="small muted">No incoming dependencies identified.</p>}<h4><ArrowUpRight size={13}/> USED BY <span>{outgoing.length}</span></h4>{outgoing.length?outgoing.slice(0,16).map(d=><Relationship key={d.id} dependency={d} entity={analysis.entities.find(e=>e.id===d.target)} onClick={()=>onDependency(d)}/>):<p className="small muted">No outgoing dependencies identified.</p>}<div className="insight-box"><Sparkles size={15}/><div><strong>A useful starting point</strong><p>{incoming.length?`Trace ${analysis.entities.find(e=>e.id===incoming[0].source)?.name || 'the upstream entity'} first to understand the data this resource needs.`:'Start with its fields and creation endpoint, then follow the resources that reference it.'}</p></div></div></>}
 {tab==='fields'&&<div className="field-list">{entity.fields.map(f=><div className="field-row" key={f.name}><div><code>{f.name}</code><small>{f.type}{f.required&&<em>required</em>}</small></div>{f.description&&<p>{f.description}</p>}{f.enum&&<div className="enum-values">{f.enum.map(v=><span key={v}>{v}</span>)}</div>}</div>)}</div>}
 {tab==='endpoints'&&<div className="endpoint-list">{ops.length?ops.map(o=><a key={o.id} href={o.source} target="_blank" rel="noreferrer"><b className={`method ${o.method}`}>{o.method}</b><strong>{o.name}</strong><code>{o.path}</code><p>{o.description.slice(0,180)}</p></a>):<p className="muted small">No endpoints associated with this entity.</p>}</div>}
 <div className="source-section"><h4>SOURCE DOCUMENTATION</h4><a href={entity.source} target="_blank" rel="noreferrer"><span><ExternalLink size={13}/>{new URL(entity.source).hostname}</span><ArrowUpRight size={14}/></a><button className="text-button" onClick={async()=>{try{await navigator.clipboard.writeText(entity.source+(entity.pointer||''));setCopied(true);setTimeout(()=>setCopied(false),1800)}catch{setCopied(false)}}}>{copied?<Check size={12}/>:<Copy size={12}/>} {copied?'Copied source':'Copy source reference'}</button></div>
 </div><div className="inspector-note"><CheckCheck size={15}/>Grounded in your documentation.</div></aside>
}
function Relationship({dependency,entity,onClick}:{dependency:Dependency;entity?:Entity;onClick:()=>void}){return <button className="relationship-card" onClick={onClick}><span className="relationship-icon" style={{color:entity?entityColor(entity).color:undefined,background:entity?entityColor(entity).soft:undefined}}><Box size={14}/></span><span><strong>{entity?.name||'Resource'}</strong><code><KeyRound size={9}/>{dependency.field}</code></span><ChevronRight size={13}/></button>}
function MouseIllustration(){return <div className="empty-illustration"><Box size={32}/><span/><span/></div>}
