'use client';
import { Component, useEffect, useRef } from 'react';
import type { ReactNode } from 'react';
import { Box, Network, X } from 'lucide-react';
import type { Boxes } from 'lucide-react';

export function download(name:string,content:string,type:string){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}

export function Metric({icon:Icon,value,label}:{icon:typeof Boxes;value:number;label:string}){return <div className="metric"><Icon size={14}/><strong>{value.toLocaleString()}</strong><span>{label}</span></div>}
export function AnalysisSettings({maxPages,setMaxPages}:{maxPages:number;setMaxPages:(n:number)=>void}){return <div className="analysis-settings"><label><span><strong>Exploration depth</strong><small>Base limit; ReadMe indexes may expand automatically</small></span><select value={maxPages} onChange={e=>setMaxPages(Number(e.target.value))}><option value={12}>Quick · 12</option><option value={24}>Standard · 24</option><option value={60}>Deep · 60</option></select></label></div>}
export function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const previous=document.activeElement as HTMLElement;const el=ref.current;const first=el?.querySelector<HTMLElement>('input,button');first?.focus();const trap=(e:KeyboardEvent)=>{if(e.key!=='Tab')return;const targets=Array.from(el?.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled]),textarea,select,a[href]')||[]);const start=targets[0],end=targets.at(-1);if(e.shiftKey&&document.activeElement===start){e.preventDefault();end?.focus()}else if(!e.shiftKey&&document.activeElement===end){e.preventDefault();start?.focus()}};el?.addEventListener('keydown',trap);return()=>{el?.removeEventListener('keydown',trap);previous?.focus()}},[]);return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="modal" ref={ref} role="dialog" aria-modal="true" aria-labelledby="modal-title"><div className="modal-header"><span className="modal-brand"><Network size={22}/></span><button className="icon-button" onClick={onClose} aria-label="Close dialog"><X size={19}/></button></div><h2 id="modal-title">{title}</h2>{children}</div></div>}
export class GraphBoundary extends Component<{children:ReactNode;onFallback:()=>void},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return{failed:true}}render(){return this.state.failed?<div className="empty-state"><Box size={30}/><h3>3D isn’t available in this browser.</h3><p>The interactive 2D map has all your entities and connections.</p><button className="primary-button" onClick={this.props.onFallback}>Return to 2D</button></div>:this.props.children}}
