import { useMemo, useState } from 'react';
import { ArrowRight, ArrowUpRight, BookOpen, Check, CheckCheck, ChevronDown, Circle, Clock3, ExternalLink, FileCode2, FileText, GitBranch, KeyRound, Search, ShieldCheck, Waypoints } from 'lucide-react';
import type { Analysis, Dependency, Operation } from '../types';
import { Status } from './Inspector';
import { parentPath } from '../requirements';
import { readBrandStorage } from '../brandStorage';

export function DependenciesView({analysis,rejected=[],onRestore,onSelect}:{analysis:Analysis;rejected?:Dependency[];onRestore?:(d:Dependency)=>void;onSelect:(d:Dependency)=>void}){
 const [query,setQuery]=useState('');const [filter,setFilter]=useState('all');
 const list=(filter==='rejected'?rejected:analysis.dependencies).filter(d=>d.type!=='schema').filter(d=>(filter==='all'||filter==='rejected'||d.type===filter) && JSON.stringify([d.field,analysis.entities.find(e=>e.id===d.source)?.name,analysis.entities.find(e=>e.id===d.target)?.name]).toLowerCase().includes(query.toLowerCase()));
 return <div className="content-view"><div className="view-heading"><div className="eyebrow">THE DATA BETWEEN THE CALLS</div><h2>Every ID has a story.</h2><p>Trace identifiers from the resource that produces them to the API that needs them.</p></div><div className="view-toolbar"><label className="search-field"><Search size={15}/><input placeholder="Find an ID or entity…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Dependency type" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All dependencies</option><option value="id">Entity IDs</option><option value="operation">Endpoint dependencies</option><option value="cross-api">Cross-API candidates</option>{rejected.length>0&&<option value="rejected">Rejected by you ({rejected.length})</option>}</select><span className="muted small">{list.length} connections</span></div><div className="dependency-table"><div className="dependency-table-head"><span>PRODUCER</span><span>IDENTIFIER / INPUT</span><span>CONSUMER</span><span>EVIDENCE</span></div>{filter==='rejected'&&<p className="small muted">Rejected links are hidden from the map, creation chains, scenarios, and flows. Restore one to bring it back.</p>}{list.slice(0,250).map(d=>filter==='rejected'?<div className="dependency-table-row rejected" key={d.id}><span>{analysis.entities.find(e=>e.id===d.source)?.name}</span><span className="id-cell"><code>{d.field}</code></span><span>{analysis.entities.find(e=>e.id===d.target)?.name}</span><span><button className="outline-button" onClick={()=>onRestore?.(d)}>Restore</button></span></div>:<button className="dependency-table-row" key={d.id} onClick={()=>onSelect(d)}><span><i className="table-dot"/>{analysis.entities.find(e=>e.id===d.source)?.name}<small>{d.sourceOperation?analysis.operations.find(o=>o.id===d.sourceOperation)?.method+' '+analysis.operations.find(o=>o.id===d.sourceOperation)?.path:'Resource'}</small></span><span className="id-cell"><KeyRound size={12}/><code>{d.field}</code><ArrowRight size={14}/></span><span>{analysis.entities.find(e=>e.id===d.target)?.name}<small>{d.targetOperation?analysis.operations.find(o=>o.id===d.targetOperation)?.method+' '+analysis.operations.find(o=>o.id===d.targetOperation)?.path:'Resource'}</small></span><span><Status status={d.status}/><ArrowUpRight size={13}/></span></button>)}</div>{!list.length&&<Empty title="No matching ID dependencies" text="Try another search or analyze additional API sources. Cross-API links are only shown when a candidate relationship is found."/>}{list.length>250&&<p className="muted small">Showing 250 matches. Narrow your search to inspect more.</p>}<div className="info-banner"><ShieldCheck size={16}/><span>Solid evidence and naming-based inference are kept separate. Click any relationship to inspect its source.</span></div></div>
}
export function OperationsView({analysis,onTrace}:{analysis:Analysis;onTrace:(id:string)=>void}){
 const [query,setQuery]=useState('');const [method,setMethod]=useState('all');const [selected,setSelected]=useState<Operation|null>(null);const [visibleCount,setVisibleCount]=useState(200);
 // Webhooks are listed as events the API sends, apart from the endpoints you call.
 const kindOf=(o:Operation)=>o.kind==='webhook'?'WEBHOOK':o.method;
 const list=analysis.operations.filter(o=>(method==='all'||kindOf(o)===method)&&`${o.name} ${o.path}`.toLowerCase().includes(query.toLowerCase()));
 const methods=['all',...new Set(analysis.operations.map(kindOf))];
 const webhookCount=list.filter(o=>o.kind==='webhook').length;
 const hasProtocolOperations=analysis.operations.some(operation=>!['GET','POST','PUT','PATCH','DELETE','HEAD','OPTIONS'].includes(operation.method));
 return <div className="content-view"><div className="view-heading"><div className="eyebrow">YOUR API, AT A GLANCE</div><h2>Explore the building blocks.</h2><p>Search operations, inspect required inputs, and understand the data returned.</p></div><div className="view-toolbar"><label className="search-field"><Search size={15}/><input placeholder="Search operations or paths…" value={query} onChange={e=>{setQuery(e.target.value);setVisibleCount(200)}}/></label><select aria-label="Operation method" value={method} onChange={e=>{setMethod(e.target.value);setVisibleCount(200)}}>{methods.map(m=><option key={m} value={m}>{m==='all'?'All methods':m}</option>)}</select><span className="small muted">{list.length-webhookCount} {hasProtocolOperations?'operations':'endpoints'}{webhookCount>0&&` · ${webhookCount} webhook events`}</span></div><div className="operations-list">{list.slice(0,visibleCount).map(o=><div key={o.id} className={`operation-item ${selected?.id===o.id?'expanded':''}`}><button onClick={()=>setSelected(selected?.id===o.id?null:o)}><b className={`method ${kindOf(o)}`}>{kindOf(o)}</b><code>{o.path}</code><span>{o.name}</span><ChevronDown size={15}/></button>{selected?.id===o.id&&<div className="operation-details"><p>{o.description||'No description provided in the specification.'}</p><div className="io-grid"><Fields title={o.kind==='webhook'?'EVENT PAYLOAD':'REQUEST INPUTS'} fields={o.kind==='webhook'?o.inputs.map(field=>({...field,location:undefined})):o.inputs}/><Fields title="RESPONSE FIELDS" fields={o.outputs}/></div><div className="operation-detail-actions">{o.entityIds[0]&&<button onClick={()=>onTrace(o.entityIds[0])}><GitBranch size={13}/>View resource dependency flow <ArrowRight size={12}/></button>}<a href={o.source} target="_blank" rel="noreferrer">Read source documentation <ExternalLink size={12}/></a></div></div>}</div>)}</div>{!list.length&&<Empty title="No operations found" text="Try a different search or method."/>}{list.length>visibleCount&&<button className="outline-button" onClick={()=>setVisibleCount(count=>count+200)}>Show 200 more · {list.length-visibleCount} remaining</button>}</div>
}
const FIELD_GROUPS:[string,string][]=[['path','PATH PARAMETERS'],['query','QUERY PARAMETERS'],['header','HEADERS'],['cookie','COOKIES'],['body','REQUEST BODY'],['argument','ARGUMENTS']];
// Mirror the providers' explorers: parameters are grouped by where they are sent, and
// nested object/array members fold under their parent instead of counting as inputs.
function Fields({title,fields}:{title:string;fields:Operation['inputs']}){
 const located=fields.some(f=>f.location);
 const groups=located?FIELD_GROUPS.map(([location,label])=>[label,fields.filter(f=>(f.location||'body')===location)] as const).filter(([,list])=>list.length):[[title,fields] as const];
 return <div>{groups.map(([label,list])=><FieldGroup key={label} title={label} fields={list}/>)}{!fields.length&&<><h4>{title} <span>0</span></h4><p className="small muted">No fields extracted.</p></>}</div>
}
function FieldGroup({title,fields}:{title:string;fields:Operation['inputs']}){
 const children=useMemo(()=>{const map=new Map<string,Operation['inputs']>();for(const f of fields){const parent=parentPath(f.name);if(parent)map.set(parent,[...(map.get(parent)||[]),f])}return map},[fields]);
 const names=new Set(fields.map(f=>f.name));
 const top=fields.filter(f=>{const parent=parentPath(f.name);return !parent||!names.has(parent)});
 return <div className="io-group"><h4>{title} <span>{top.length}</span></h4>{top.map(f=><FieldRow key={f.name} field={f} childMap={children}/>)}</div>
}
function FieldRow({field,childMap,depth=0}:{field:Operation['inputs'][number];childMap:Map<string,Operation['inputs']>;depth?:number}){
 const [open,setOpen]=useState(false);const nested=childMap.get(field.name)||[];
 const label=depth?field.name.slice((parentPath(field.name)||'').length).replace(/^(?:\[\])?\./,''):field.name;
 return <><div className="io-field" style={{paddingLeft:depth*12}}>{nested.length?<button className="io-toggle" aria-expanded={open} onClick={()=>setOpen(!open)}><ChevronDown size={10} className={open?'':'collapsed'}/><code>{label}</code></button>:<code>{label}</code>}<span>{field.type}</span>{nested.length>0&&!open&&<em>{nested.length} fields</em>}{field.required&&<small>required</small>}</div>{open&&nested.map(child=><FieldRow key={child.name} field={child} childMap={childMap} depth={depth+1}/>)}</>
}

export function StudyView({analysis,onExplore}:{analysis:Analysis;onExplore:(id:string)=>void}){
 const [completed,setCompleted]=useState<number[]>(()=>{try{return JSON.parse(readBrandStorage('apipassage-study-'+analysis.id,'atlas-study-'+analysis.id)||'[]')}catch{return []}});const [active,setActive]=useState(0);
 const ranked=useMemo(()=>[...analysis.entities].sort((a,b)=>analysis.dependencies.filter(d=>d.source===b.id||d.target===b.id).length-analysis.dependencies.filter(d=>d.source===a.id||d.target===a.id).length),[analysis]);
 const steps=[{title:'Get the big picture',time:4,subtitle:'Meet the API and its core resources',description:`Start with ${analysis.name}. Identify what each core resource represents and where it belongs in the system.`,action:'Explore a central entity',entities:ranked.slice(0,5)}, {title:'Understand the data model',time:7,subtitle:'Entities, fields, and relationships',description:'Read the key fields of each resource. Separate embedded objects from references to other entities. Look for required fields and lifecycle states.',action:'Inspect entity fields',entities:ranked.slice(0,4)}, {title:'Follow the IDs',time:8,subtitle:'Producer → identifier → consumer',description:'For each connection, identify who produces the ID and who needs it. Check whether it is required and whether the relationship is documented or inferred.',action:'Trace this entity',entities:ranked.slice(0,3)}, {title:'Walk through a workflow',time:7,subtitle:'Prerequisites, requests, and responses',description:'Pick a creation endpoint. Work backwards through its required inputs, then follow the resources that consume its response. Review conditional behavior in the source.',action:'Explore a workflow',entities:ranked.filter(e=>analysis.operations.some(o=>o.method==='POST'&&o.entityIds.includes(e.id))).slice(0,3)}, {title:'Check the edge cases',time:4,subtitle:'Authentication, retries, and coverage',description:'Review authentication and other extracted design patterns. Identify unverified dependencies and unread sources before relying on the map.',action:'Review a resource',entities:ranked.slice(0,2)}];
 const toggle=(index:number)=>{const next=completed.includes(index)?completed.filter(i=>i!==index):[...completed,index];setCompleted(next);localStorage.setItem('apipassage-study-'+analysis.id,JSON.stringify(next))};
 const current=steps[active];
 return <div className="content-view study-view"><div className="study-heading"><span className="study-icon"><BookOpen size={24}/></span><div><div className="eyebrow">LESS READING. MORE UNDERSTANDING.</div><h2>Your 30-minute API briefing.</h2><p>A focused path through the essentials. Depth depends on the API and available documentation.</p></div><span className="time-pill"><Clock3 size={14}/>30 min</span></div><div className="study-progress"><span>{completed.length} of 5 chapters complete</span><div><i style={{width:`${completed.length/5*100}%`}}/></div><strong>{completed.length*20}%</strong></div><div className="study-layout"><div className="chapter-list">{steps.map((step,i)=><button key={step.title} className={active===i?'active':''} onClick={()=>setActive(i)}><span className={`chapter-number ${completed.includes(i)?'complete':''}`}>{completed.includes(i)?<Check size={16}/>:String(i+1).padStart(2,'0')}</span><span><strong>{step.title}</strong><small>{step.subtitle}</small></span><em>{step.time}m</em></button>)}</div><div className="chapter-content"><div className="eyebrow">CHAPTER {String(active+1).padStart(2,'0')} · {current.time} MINUTES</div><h2>{current.title}</h2><p>{current.description}</p><h4>START HERE</h4>{current.entities.map(e=><button className="study-entity" key={e.id} onClick={()=>onExplore(e.id)}><span><Waypoints size={17}/><strong>{e.name}</strong></span><ArrowUpRight size={16}/></button>)}{active===4&&<div className="study-patterns">{analysis.patterns.slice(0,4).map(p=><p key={p.name}><strong>{p.name}.</strong> {p.detail}</p>)}<p>{analysis.warnings[0]}</p></div>}<div className="chapter-check"><strong>Check your understanding</strong><p>{['Can you explain the purpose of the three most connected entities?','Which fields connect one entity to another?','Where does each required ID come from?','Which conditions could change the order or outcome of your calls?','Which relationships still need verification?'][active]}</p></div><button className="primary-button" onClick={()=>{toggle(active);if(!completed.includes(active)&&active<4)setActive(active+1)}}>{completed.includes(active)?<CheckCheck size={16}/>:<Check size={16}/>} {completed.includes(active)?'Completed · mark incomplete':'Mark complete & continue'}</button></div></div></div>
}
export function PatternsView({analysis}:{analysis:Analysis}){return <div className="content-view"><div className="view-heading"><div className="eyebrow">THE RULES OF THE API</div><h2>Understand its design language.</h2><p>Authentication, conventions, and behavioral patterns extracted from your sources.</p></div><div className="pattern-grid">{analysis.patterns.map((p,i)=><article key={`${p.name}-${i}`}><span className="pattern-icon">{i%2?<Waypoints size={20}/>:<ShieldCheck size={20}/>}</span><h3>{p.name}</h3>{p.inferred&&<Status status="inferred"/>}<p>{p.detail}</p><a href={p.source} target="_blank" rel="noreferrer">Read source <ArrowUpRight size={14}/></a></article>)}</div>{!analysis.patterns.length&&<Empty title="No design patterns extracted yet" text="No design patterns were found in the parsed specification."/>}</div>}
export function SourcesView({analysis}:{analysis:Analysis}){const coverage=analysis.coverage;const cards:Array<[number,string]>=[[coverage.specifications,'Specifications'],[coverage.pagesRead,'Pages read'],[coverage.discovered,'Links discovered']];if(coverage.referencePagesIndexed!==undefined)cards.push([coverage.referencePagesRead||0,`Reference pages read / ${coverage.referencePagesIndexed} indexed`],[coverage.referencePagesParsed||0,'Reference pages parsed']);return <div className="content-view"><div className="view-heading"><div className="eyebrow">KNOW WHAT YOU KNOW</div><h2>Evidence, with the gaps included.</h2><p>Your map is only as complete as its sources. Here is exactly what was covered.</p></div><div className="coverage-cards">{cards.map(([n,label])=><div key={label}><strong>{n}</strong><span>{label}</span></div>)}</div>{coverage.schemaCount!==undefined&&<p className="schema-coverage-note"><strong>{coverage.resourceCount}</strong> endpoint resources mapped from <strong>{coverage.schemaCount}</strong> schema models. {coverage.groupedSchemas ?? coverage.schemaCount} schema variants grouped under resources; {coverage.supportingSchemas ?? 0} supporting or error models excluded from the resource graph.</p>}{coverage.referencePagesIndexed!==undefined&&<p className="schema-coverage-note">The index listed <strong>{coverage.referencePagesIndexed}</strong> reference pages. <strong>{coverage.referencePagesUnread||0}</strong> were not fetched; <strong>{coverage.referencePagesUnparsed||0}</strong> contained an OpenAPI definition that could not be parsed. Reference pages may also be category overviews, so this is a page inventory, not an endpoint count.</p>}<div className="warnings-box"><h4><Circle size={12}/> COVERAGE NOTES</h4>{analysis.warnings.map((w,i)=><p key={i}>{w}</p>)}</div><div className="sources-list">{analysis.sources.map((s,i)=><a key={`${s.url}-${i}`} href={s.url} target="_blank" rel="noreferrer">{s.kind==='spec'?<FileCode2 size={18}/>:<FileText size={18}/>}<span><strong>{s.title}</strong><small>{s.url}</small></span><em>{s.status}</em><ExternalLink size={14}/></a>)}</div></div>}
export function Empty({title,text}:{title:string;text:string}){return <div className="empty-state"><Search size={27}/><h3>{title}</h3><p>{text}</p></div>}
