// Generates src/theme-dark.css from src/styles.css: every color keeps its hue and
// saturation while its lightness is flipped, so light surfaces become dark and dark
// text becomes light. Runs before `dev` and `build`; do not edit the output by hand.
import { readFileSync, writeFileSync } from 'node:fs';

const source = readFileSync(new URL('../src/styles.css', import.meta.url), 'utf8');
const hexToRgb = hex => { const h = hex.length <= 4 ? [...hex.slice(1)].map(c => c + c).join('') : hex.slice(1); return [0, 2, 4].map(i => parseInt(h.slice(i, i + 2), 16) / 255).concat(h.length === 8 ? [parseInt(h.slice(6, 8), 16) / 255] : []); };
const rgbToHsl = ([r, g, b]) => { const max = Math.max(r, g, b), min = Math.min(r, g, b); const l = (max + min) / 2; if (max === min) return [0, 0, l]; const d = max - min; const s = l > .5 ? d / (2 - max - min) : d / (max + min); const h = max === r ? (g - b) / d + (g < b ? 6 : 0) : max === g ? (b - r) / d + 2 : (r - g) / d + 4; return [h / 6, s, l]; };
const hslToHex = ([h, s, l], alpha) => { const f = n => { const k = (n + h * 12) % 12; const a = s * Math.min(l, 1 - l); return Math.round((l - a * Math.max(-1, Math.min(k - 3, 9 - k, 1))) * 255).toString(16).padStart(2, '0'); }; return `#${f(0)}${f(8)}${f(4)}${alpha === undefined ? '' : Math.round(alpha * 255).toString(16).padStart(2, '0')}`; };
// Flip lightness into a comfortable range: white -> #14131c-ish, near-black -> #ecebf2-ish.
// Text keeps a lightness floor so muted greys stay readable on dark surfaces.
const flip = (hex, text = false) => { const [r, g, b, a] = hexToRgb(hex); const [h, s, l] = rgbToHsl([r, g, b]); const accent = s > .35 && l > .3 && l < .75; let next = accent ? Math.min(.78, Math.max(.6, 1 - l + .12)) : .09 + (1 - l) * .84; if (text) next = Math.max(next, .66);
  if (text && l < .2) next = Math.max(next, .9); return hslToHex([h, accent ? Math.min(s, .7) : s * .6, next], a); };
const isText = declaration => /^(?:color|fill|--ink|--muted)\s*:/i.test(declaration);

const rules = [];
const walk = (css, wrap) => {
  const pattern = /(@media[^{]+)\{((?:[^{}]*\{[^{}]*\})*[^{}]*)\}|([^{}@]+)\{([^{}]*)\}/g;
  for (const match of css.matchAll(pattern)) {
    if (match[1]) { walk(match[2], match[1].trim()); continue; }
    const body = match[4].split(';').map(item => item.trim()).filter(item => /#[0-9a-f]{3,8}\b/i.test(item) && /^(?:color|background(?:-color)?|border(?:-[a-z]+)?(?:-color)?|box-shadow|fill|stroke|--[a-z-]+)\s*:/i.test(item));
    if (!body.length) continue;
    const selectors = match[3].split(',').map(item => item.trim()).filter(Boolean).map(item => item.startsWith(':root') ? item.replace(':root', ':root[data-theme="dark"]') : `:root[data-theme="dark"] ${item}`);
    const declarations = body.map(item => item.replace(/#[0-9a-f]{3,8}\b/gi, hex => flip(hex, isText(item)))).join(';');
    rules.push(`${wrap ? `${wrap}{` : ''}${selectors.join(',')}{${declarations}}${wrap ? '}' : ''}`);
  }
};
walk(source.replace(/\/\*[\s\S]*?\*\//g, '').replace(/@import[^\n]*\n/g, ''), null);
const extra = `:root[data-theme="dark"]{color-scheme:dark}:root[data-theme="dark"] body{background:#14131c;color:#e7e5f0}
:root[data-theme="dark"] input,:root[data-theme="dark"] select,:root[data-theme="dark"] textarea{background:#1d1b28;color:#e7e5f0;border-color:#34304a}
:root[data-theme="dark"] .react-flow__controls-button{background:#1d1b28;fill:#d8d4e8;border-color:#34304a}:root[data-theme="dark"] .react-flow__minimap{background:#1d1b28!important}`;
writeFileSync(new URL('../src/theme-dark.css', import.meta.url), `/* Generated by scripts/dark-theme.mjs from styles.css. Do not edit. */\n${rules.join('\n')}\n${extra}\n`);
console.log(`dark theme: ${rules.length} rules`);
