import type { Analysis, Entity, Field, Operation, Dependency } from './types';
const base='https://apidocs.chargebee.com/docs/api/';
const f=(name:string,type='string',required=false,description=''):Field=>({name,type,required,description});
const entities:Entity[]=[
 {id:'customer',name:'Customer',group:'Customers',description:'The person or organization subscribing to your products. A customer connects subscriptions, billing details, and payment sources.',fields:[f('id','string',true,'Unique identifier of the customer.'),f('email'),f('first_name'),f('auto_collection','enum',false,'Controls automatic payment collection.'),f('primary_payment_source_id','string',false,'Preferred payment source for this customer.')],source:base+'customers'},
 {id:'subscription',name:'Subscription',group:'Subscriptions',description:'Connects a customer to the products they subscribe to. Defines the recurring billing schedule, lifecycle, and the item prices included in their subscription.',fields:[f('id','string',true,'Unique identifier of the subscription.'),f('customer_id','string',true,'Identifier of the customer with whom this subscription is associated.'),f('subscription_items[].item_price_id','string',true,'Identifier of an item price in the subscription.'),{...f('status','enum',true,'Current lifecycle state.'),enum:['future','in_trial','active','non_renewing','paused','cancelled']},f('current_term_end','timestamp',false,'End of the current billing period.')],source:base+'subscriptions'},
 {id:'invoice',name:'Invoice',group:'Billing',description:'Records the charges billed to a customer. An invoice can contain charges from multiple subscriptions when consolidated invoicing is enabled.',fields:[f('id','string',true),f('customer_id','string',true),f('subscription_id','string',false,'May be null for consolidated invoices. Use the subscription ID on each line item.'),f('linked_payments[].txn_id','string',false,'Identifier of a transaction applied to the invoice.'),f('total','integer',true),f('status','enum',true)],source:base+'invoices'},
 {id:'item-family',name:'Item family',group:'Product catalog',description:'Groups related catalog items. When Product Families are enabled, an item references an existing item family.',fields:[f('id','string',true,'Unique identifier of the item family.'),f('name','string',true,'Display name for the family.')],source:base+'item_families/create-an-item-family'},
 {id:'item',name:'Item',group:'Product catalog',description:'A product or service in your catalog. Items can represent plans, addons, or one-time charges.',fields:[f('id','string',true),f('name','string',true),f('item_family_id','string',false,'Required when Product Families are enabled; references an existing item family.'),f('type','enum',true)],source:base+'items'},
 {id:'item-price',name:'Item price',group:'Product catalog',description:'A price point for a catalog item. Defines its currency, pricing model, amount, and billing interval.',fields:[f('id','string',true),f('item_id','string',true,'The id of the item that the item price belongs to.'),f('currency_code','string',true),f('price','integer'),f('period','integer')],source:base+'item_prices'},
 {id:'payment-source',name:'Payment source',group:'Payments',description:'A payment instrument associated with a customer, such as a card or bank account.',fields:[f('id','string',true),f('customer_id','string',true),f('type','enum',true),f('status','enum',true)],source:base+'payment_sources'},
 {id:'transaction',name:'Transaction',group:'Payments',description:'Records a payment, refund, or authorization. A transaction can be applied to an invoice.',fields:[f('id','string',true),f('customer_id','string',true),f('payment_source_id','string'),f('amount','integer',true),f('status','enum',true)],source:base+'transactions'},
 {id:'credit-note',name:'Credit note',group:'Billing',description:'Tracks credits issued against an invoice, including adjustments and refundable credits.',fields:[f('id','string',true),f('customer_id','string',true),f('reference_invoice_id','string'),f('total','integer',true)],source:base+'credit_notes'},
 {id:'event',name:'Event',group:'Events',description:'A record of a change to a resource. Configured webhooks deliver event payloads to your application; duplicates and out-of-order delivery must be handled.',fields:[f('id','string',true),f('event_type','enum',true),f('content','object',true),f('occurred_at','timestamp',true)],source:base+'events'},
].map(e=>({...e,api:'Chargebee',operationIds:[],kind:'entity'}));
const operations:Operation[]=[
 {id:'create-customer',name:'Create a customer',method:'POST',path:'/customers',entityIds:['customer'],description:'Creates a customer record. Its returned ID can be used when creating a subscription for an existing customer.',inputs:[f('email'),f('first_name')],outputs:[f('customer.id','string',true)],source:base+'customers/create-a-customer'},
 {id:'get-customer',name:'Retrieve a customer',method:'GET',path:'/customers/{customer-id}',entityIds:['customer'],description:'Retrieves the customer identified by the path parameter.',inputs:[f('customer-id','string',true)],outputs:[f('customer','object',true)],source:base+'customers/retrieve-a-customer'},
 {id:'create-item-family',name:'Create an item family',method:'POST',path:'/item_families',entityIds:['item-family'],description:'Creates an item family when Product Families are enabled.',inputs:[f('id','string',true),f('name','string',true)],outputs:[f('item_family.id','string',true)],source:base+'item_families/create-an-item-family'},
 {id:'create-item',name:'Create an item',method:'POST',path:'/items',entityIds:['item','item-family'],description:'Creates a catalog item. item_family_id must reference an existing family when Product Families are enabled.',inputs:[f('id','string',true),f('name','string',true),f('item_family_id','string',false,'Required when Product Families are enabled.')],outputs:[f('item.id','string',true)],source:base+'items/create-an-item'},
 {id:'create-item-price',name:'Create an item price',method:'POST',path:'/item_prices',entityIds:['item-price','item'],description:'Creates a price point for an existing catalog item.',inputs:[f('id','string',true),f('name','string',true),f('item_id','string',true)],outputs:[f('item_price.id','string',true)],source:base+'item_prices/create-an-item-price'},
 {id:'create-subscription',name:'Create a subscription',method:'POST',path:'/customers/{customer-id}/subscription_for_items',entityIds:['subscription','customer','item-price'],description:'Creates a subscription for an existing customer using catalog item prices. Billing behavior depends on trial, collection, and site settings.',inputs:[f('customer-id','string',true),f('subscription_items[item_price_id][0]','string',true)],outputs:[f('subscription.id','string',true),f('customer','object',true),f('invoice','object',false)],source:base+'subscriptions/create-subscription-for-items'},
 {id:'get-subscription',name:'Retrieve a subscription',method:'GET',path:'/subscriptions/{subscription-id}',entityIds:['subscription'],description:'Retrieves the subscription and associated customer.',inputs:[f('subscription-id','string',true)],outputs:[f('subscription','object',true),f('customer','object',true)],source:base+'subscriptions/retrieve-a-subscription'},
 {id:'get-invoice',name:'Retrieve an invoice',method:'GET',path:'/invoices/{invoice-id}',entityIds:['invoice'],description:'Retrieves a specific invoice, including its charges and linked payments.',inputs:[f('invoice-id','string',true)],outputs:[f('invoice','object',true)],source:base+'invoices/retrieve-an-invoice'},
 {id:'get-event',name:'Retrieve an event',method:'GET',path:'/events/{event-id}',entityIds:['event'],description:'Retrieves a recorded event and its resource payload.',inputs:[f('event-id','string',true)],outputs:[f('event','object',true)],source:base+'events/retrieve-an-event'},
];
entities.forEach(e=>e.operationIds=operations.filter(o=>o.entityIds.includes(e.id)).map(o=>o.id));
const relations:[string,string,string,string][]=[
 ['customer','subscription','customer_id','The subscription identifies its associated customer through customer_id.'],
 ['item-family','item','item_family_id','When Product Families are enabled, item_family_id must reference an existing item family.'],
 ['item','item-price','item_id','Each item price belongs to a catalog item.'],
 ['item-price','subscription','subscription_items[].item_price_id','Subscription items reference the catalog item prices being purchased.'],
 ['customer','payment-source','customer_id','Payment sources are associated with a customer.'],
 ['subscription','invoice','subscription_id','Charges in a subscription are billed through invoices. With consolidated invoicing, inspect subscription_id on invoice line items.'],
 ['customer','invoice','customer_id','The invoice belongs to the customer identified by customer_id.'],
 ['payment-source','transaction','payment_source_id','The transaction can reference the payment source used.'],
 ['transaction','invoice','linked_payments[].txn_id','An invoice lists transactions applied to it in linked_payments.'],
 ['invoice','credit-note','reference_invoice_id','A credit note can reference the invoice it adjusts.'],
 ['subscription','event','content.subscription','Subscription events can include the affected subscription in the event payload.'],
];
const dependencies:Dependency[]=relations.map(([source,target,field,evidence],i)=>({id:`demo-${i}`,source,target,field,evidence,type:target==='event'?'schema':'id',status:'documented',sourceUrl:entities.find(e=>e.id===target)!.source,...(field==='subscription_id'&&target==='invoice'?{required:false}:{})}));
dependencies.push({id:'op-customer-subscription',source:'customer',target:'subscription',field:'customer.id → customer-id',type:'operation',status:'documented',evidence:'The create-subscription endpoint requires an existing customer. Use the customer identifier in the request path.',sourceUrl:base+'subscriptions/create-subscription-for-items',sourceOperation:'create-customer',targetOperation:'create-subscription',required:true});
export const demo:Analysis={id:'chargebee-example',name:'Chargebee API',version:'v2 · Product Catalog 2.0',createdAt:'2026-09-24T00:00:00Z',urls:[base+'getting-started'],entities,operations,dependencies,patterns:[{name:'Authentication',detail:'HTTP Basic authentication. The API key is the username and the password is empty. Test and live sites use different keys.',source:base+'auth'},{name:'Idempotency',detail:'Supported POST requests accept chargebee-idempotency-key. The documented replay window is 30 minutes. Estimate APIs are excluded.',source:base+'idempotency'},{name:'Event delivery',detail:'Webhook deliveries can be duplicated and arrive out of order. Deduplicate by event ID and use resource_version to compare resource updates.',source:base+'events'},{name:'Conditional billing',detail:'Creating a subscription does not always imply immediate payment. Trials, collection settings, pending invoices, and net terms change the flow.',source:base+'subscriptions'}],warnings:['This is a curated, partial example for exploring APIPassage. Run an analysis to discover the current documentation.'],sources:entities.map(e=>({url:e.source,title:e.name,kind:'page',status:'example reference'})),coverage:{pagesRead:9,specifications:0,discovered:9,attempted:9,pageLimit:24,aiPages:0,complete:false},mode:'example',demo:true};
