export interface Field {name:string;type:string;required:boolean;description:string;enum?:string[];location?:string;ref?:string}
export interface Entity {id:string;name:string;rawName?:string;api:string;group:string;description:string;fields:Field[];source:string;pointer?:string;operationIds:string[];kind:string;schemaNames?:string[]}
export interface Operation {id:string;name:string;method:string;path:string;description:string;inputs:Field[];outputs:Field[];entityIds:string[];source:string;tags?:string[];kind?:'webhook';contentType?:string}
export interface Dependency {id:string;source:string;target:string;field:string;type:'id'|'schema'|'operation'|'cross-api';status:'documented'|'inferred';evidence:string;sourceUrl:string;quote?:string;sourceOperation?:string;targetOperation?:string;required?:boolean;extraction?:string;review?:'confirmed'}
export interface Pattern {name:string;detail:string;source:string;inferred?:boolean}
export interface Analysis {id:string;name:string;version:string;createdAt:string;urls:string[];entities:Entity[];operations:Operation[];dependencies:Dependency[];patterns:Pattern[];warnings:string[];sources:{url:string;title:string;kind:string;status:string}[];coverage:{pagesRead:number;specifications:number;discovered:number;attempted:number;pageLimit:number;aiPages?:number;complete:boolean;schemaCount?:number;groupedSchemas?:number;supportingSchemas?:number;resourceCount?:number;canonicalVersion?:number;referencePagesIndexed?:number;referencePagesRead?:number;referencePagesParsed?:number;referencePagesUnparsed?:number;referencePagesUnread?:number};mode:string;demo:boolean;jobId?:string;schemaVersion?:number;docsUrl?:string|null;servers?:string[];changes?:import('./analysisDiff').AnalysisChanges}
export interface SavedAnalysis {sourceKey:string;id:string;name:string;version:string;createdAt:string;urls:string[];mode:string;canonicalVersion:number;entityCount:number;operationCount:number;dependencyCount:number}
export interface Job {id:string;status:string;progress:number;stage:string;message:string;error?:string;result?:Analysis;events:{stage:string;progress:number;message:string;time:number}[]}
export type View='workspace'|'graph'|'dependencies'|'operations'|'scenarios'|'study'|'patterns'|'sources';
export const palette=[{color:'#7d62db',soft:'#f1edff',name:'violet'},{color:'#438ecb',soft:'#eaf5ff',name:'blue'},{color:'#c78a39',soft:'#fff5e6',name:'amber'},{color:'#45a187',soft:'#e9f7f1',name:'green'},{color:'#ca7297',soft:'#fceef5',name:'pink'},{color:'#6e88bb',soft:'#edf2fa',name:'slate'}];
export function entityColor(entity:Entity) {let hash=0;for(const c of entity.group)hash=(hash*31+c.charCodeAt(0))>>>0;return palette[hash%palette.length]}
export const isEndpoint=(operation:Operation)=>operation.kind!=='webhook';
export const displayName=(name:string)=>name.replace(/ API(?: Documentation| Reference)?$/i,'').replace(/ documentation$/i,'');
